### ISSUE TITLE
Build fails on missing linked SSL library

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#1615]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [X] 5.4.6
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Change introduced by https://github.com/OpenNebula/one/commit/771c93c42cab9e3d2476afe781aa52323bb50126 breaks the OpenNebula build on Ubuntu and Debian (not sure why the CentOS target works fine).

### Actual Behavior

```
g++ -o src/im_mad/collectd/collectd -Wl,-z,relro -Wl,--as-needed -g -pthread src/im_mad/collectd/collectd.o -Lsrc/common -Lsrc/log -Lsrc/raft -Lsrc/sql -Lsrc/host -Lsrc/cluster -Lsrc/datastore -Lsrc/group -Lsrc/mad -Lsrc/nebula -Lsrc/pool -Lsrc/template -Lsrc/vm -Lsrc/vm_group -Lsrc/vm_template -Lsrc/vmm -Lsrc/lcm -Lsrc/tm -Lsrc/dm -Lsrc/im -Lsrc/image -Lsrc/rm -Lsrc/vnm -Lsrc/hm -Lsrc/um -Lsrc/authm -Lsrc/acl -Lsrc/xml -Lsrc/document -Lsrc/zone -Lsrc/client -Lsrc/secgroup -Lsrc/vdc -Lsrc/vrouter -Lsrc/market -Lsrc/ipamm -L/build/xmlrpc-c/install/lib -L/build/xmlrpc-c/install/lib64 -L/usr/lib/x86_64-linux-gnu -L/build/xmlrpc-c/install/lib -Lsrc/im_mad/collectd -lim_collectd -lnebula_common -lutil -lsqlite3 -lmysqlclient -lz -lm -ldl -lxmlrpc_server_abyss++ -lxmlrpc_server++ -lxmlrpc_abyss++ -lxmlrpc_server_abyss -lxmlrpc_server -lxmlrpc_abyss -lxmlrpc_client++ -lxmlrpc_client -lxmlrpc++ -lxmlrpc_util++ -lxmlrpc -lxmlrpc_util -lpthread -lxmlrpc_packetsocket -lxml2
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::base64_encode(std::string const&)':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:108: undefined reference to `BIO_f_base64'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:108: undefined reference to `BIO_new'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:109: undefined reference to `BIO_s_mem'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:109: undefined reference to `BIO_new'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:111: undefined reference to `BIO_push'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:113: undefined reference to `BIO_set_flags'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:115: undefined reference to `BIO_write'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:117: undefined reference to `BIO_ctrl'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:122: undefined reference to `BIO_ctrl'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:126: undefined reference to `BIO_free_all'
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::base64_decode(std::string const&)':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:146: undefined reference to `BIO_f_base64'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:146: undefined reference to `BIO_new'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:148: undefined reference to `BIO_s_mem'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:148: undefined reference to `BIO_new'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:149: undefined reference to `BIO_s_mem'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:149: undefined reference to `BIO_new'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:151: undefined reference to `BIO_push'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:153: undefined reference to `BIO_set_flags'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:155: undefined reference to `BIO_write'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:159: undefined reference to `BIO_write'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:157: undefined reference to `BIO_read'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:162: undefined reference to `BIO_ctrl'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:166: undefined reference to `BIO_free_all'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:167: undefined reference to `BIO_free_all'
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::sha1_digest(std::string const&)':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:184: undefined reference to `EVP_MD_CTX_init'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:189: undefined reference to `EVP_sha1'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:189: undefined reference to `EVP_DigestInit_ex'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:191: undefined reference to `EVP_DigestUpdate'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:193: undefined reference to `EVP_DigestFinal_ex'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:196: undefined reference to `EVP_MD_CTX_cleanup'
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::aes256cbc_encrypt(std::string const&, std::string)':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:227: undefined reference to `EVP_CIPHER_CTX_init'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:232: undefined reference to `EVP_aes_256_cbc'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:232: undefined reference to `EVP_EncryptInit'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:233: undefined reference to `EVP_EncryptUpdate'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:234: undefined reference to `EVP_EncryptFinal'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:237: undefined reference to `EVP_CIPHER_CTX_cleanup'
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::SSLMutex::SSLMutex()':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:599: undefined reference to `CRYPTO_num_locks'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:607: undefined reference to `CRYPTO_set_id_callback'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:610: undefined reference to `CRYPTO_set_locking_callback'
src/common/libnebula_common.a(NebulaUtil.o): In function `one_util::SSLMutex::~SSLMutex()':
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:615: undefined reference to `CRYPTO_num_locks'
/build/opennebula-5.4.6/src/common/NebulaUtil.cc:621: undefined reference to `CRYPTO_set_locking_callback'
collect2: error: ld returned 1 exit status
scons: *** [src/im_mad/collectd/collectd] Error 1
scons: building terminated because of errors.
debian/rules:26: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/build/opennebula-5.4.6'
debian/rules:23: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

# Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix b
