### ISSUE TITLE
Sunstone can't log in after upgrade CE 6.4 to 6.6.1

### ISSUE THREAD

**Issue by kvakanet** [OpenNebula/one#6369]
**Description**
After upgrade on Almalinux8 Opennebula CE 6.4.0 to CE 6.6.1.1 can not login into sunstone.
Got message: Internal server error.
On server with older install opennebula 6.6.0 CE problem not found. (Maybe if you update the problem will appear.)

**To Reproduce**
Install opennebula 6.4.0 CE on Almalinux8 and upgrade to opennebula 6.6.1.1 CE.

**Expected behavior**
Login into Sunstone

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.6.1.1 CE

**Additional context**
Into /var/log/messages:
```
Oct 28 09:24:36 host1 opennebula-sunstone[60682]: == Sinatra (v2.2.2) has taken the stage on 9869 for production with backup from Thin                                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: 2023-10-28 09:25:04 - NoMethodError - undefined method `downcase' for nil:NilClass:                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/lib/one/sunstone/views/index.erb:67:in `__tilt_47065867425920'                                                                                          
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `call'                                                                                 
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:181:in `evaluate'                                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/tilt-2.0.11/lib/tilt/template.rb:109:in `render'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:863:in `render'                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:711:in `erb'                                                                                 
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/lib/one/sunstone/sunstone-server.rb:711:in `block in <main>'                                                                                            
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1693:in `call'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1693:in `block in compile!'                                                                  
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'                                                         
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1049:in `route_eval'                                                                         
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'                                                         
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1078:in `block in process_route'                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1076:in `catch'                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1076:in `process_route'                                                                      
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1028:in `block in route!'                                                                    
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1025:in `each'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1025:in `route!'                                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1147:in `block in dispatch!'                                                                 
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'                                                                    
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'                                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1142:in `dispatch!'                                                                          
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `block in call!'                                                                      
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `block in invoke'                                                                    
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `catch'                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1119:in `invoke'                                                                             
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:956:in `call!'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:945:in `call'                                                                                
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'                                                                              
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:255:in `call'                                                                                
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/deflater.rb:44:in `call'                                                                                   
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'                                                                    
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'                                                                       
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-protection-2.2.3/lib/rack/protection/xss_header.rb:18:in `call'                                                           
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-protection-2.2.3/lib/rack/protection/path_traversal.rb:16:in `call'                                                       
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-protection-2.2.3/lib/rack/protection/json_csrf.rb:26:in `call'                                                            
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-protection-2.2.3/lib/rack/protection/base.rb:50:in `call'                                                                 
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-protection-2.2.3/lib/rack/protection/frame_options.rb:31:in `call'                                                        
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'                                                                                
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'                                                                                       
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'                                                                            
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:218:in `call'                                                                                
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:2000:in `call'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1560:in `block in call'                                                                      
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1776:in `synchronize'                                                                        
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/sinatra-2.2.3/lib/sinatra/base.rb:1560:in `call'                                                                               
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'                                                                 
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'                                                                                
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'                                                                          
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/thin-1.8.1/lib/thin/connection.rb:50:in `block in process'                                                                     
Oct 28 09:25:04 host1 opennebula-sunstone[60682]: #011/usr/share/one/gems-dist/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'                                                     

```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by jloboescalona2** [comment]
@kvakanet hello, can you pass me the sunstone-server.conf file to test? 
it looks like you have misconfigured the ` public_fireedge_endpoint`

**Comment by kvakanet** [comment]
Hello @jloboescalona2 !
Into my sunstone-server.conf was commented strings
```
################################################################################                                                                                                                                   
# FireEdge                                                                                                                                                                                                         
################################################################################                                                                                                                                   
                                                                                                                                                                                                                   
#:private_fireedge_endpoint: http://localhost:2616                                                                                                                                                                 
#:public_fireedge_endpoint: http://localhost:2616                                                                                                                                                                   
``` 
After uncomment param :public_fireedge_endpoint: http://localhost:2616 sunstone is work. (but warning on fireedge)

P.S. I not used fireedge. (Docs: https://docs.opennebula.io/6.6/intro_release_notes/upgrades/upgrading_single.html?highlight=public_fireedge_endpoint. **If you don’t want to use the new feature, comment these out in order to get rid of the error.**)

**Comment by Githopp192** [comment]
same to me after upgrading to CD6.6.1.1 - login to SUNSTONE not possible (INTERNAL SERVER ERROR).

After uncommenting : 

#:private_fireedge_endpoint: http://localhost:2616                                                                                                                                                                 
#:public_fireedge_endpoint: http://localhost:2616         

.. sunstone login is working again (but with warnings).

Server: RHEL 8.9

**Comment by tinova** [comment]
closing as this seems a configuration issue. please input valid values for FireEdge public and private endpoint, FireEdge is a requirement to use VNC/RDP capabilities.

**Comment by Githopp192** [comment]
for me the statement is clear:

:private_fireedge_endpoint: http://localhost:2616
:public_fireedge_endpoint: http://localhost:2616

If you don’t want to use the new feature, comment these out in order to get rid of the error.

![image](https://github.com/OpenNebula/one/assets/32612067/77d40b1a-b9a5-4020-907b-ad480cc39979)

in OpenNebula 6.4.x commenting those lines did work and sunstone login was possible.

What i tried so far:

- apt remove opennebula-fireedge

Result: same "INTERNAL SERVER ERROR" 

- enable again:

:private_fireedge_endpoint: http://localhost:2616
:public_fireedge_endpoint: http://localhost:2616

![image](https://github.com/OpenNebula/one/assets/32612067/b3228110-b513-4ba4-a25a-73ccf1b93d98)


Result: same "INTERNAL SERVER ERROR"  (when login in sunstone-gui  - cannot see logic, because opennebula-fireedge was un-installed completely)

Tried also:

To change the serveradmin password, follow the next steps:

oneuser passwd 1 --sha256 <PASSWORD>
echo 'serveradmin:PASSWORD' > /var/lib/one/.one/oneflow_auth
echo 'serveradmin:PASSWORD' > /var/lib/one/.one/ec2_auth
echo 'serveradmin:PASSWORD' > /var/lib/one/.one/onegate_auth
echo 'serveradmin:PASSWORD' > /var/lib/one/.one/occi_auth
echo 'serveradmin:PASSWORD' > /var/lib/one/.one/sunstone_auth

and

oneuser passwd 0 <PASSWORD>
echo 'oneadmin:PASSWORD' > /var/lib/one/.one/one_auth

for me it seems not a configration issue .. 

Best 
Mike

**Comment by Githopp192** [comment]
Got it to solve !

Within OpenNebula 6.6 - if you want get rid of "public endpoint is not working, please contact your cloud administrator " ==>

https://docs.opennebula.io/6.6/installation_and_configuration/opennebula_services/sunstone.html?highlight=public%20endpoint

To disable using fireedge you can set both of the endpoints to be '' which will cause sunstone to fall back to the noVNC server for VNC access

:private_fireedge_endpoint: ''
:public_fireedge_endpoint: ''

It seem there is a missmatch in the ON 6.6 Documentation _"If you don't  to use the new feature, comment these out in order to get rod of the error.

only uncomment like "# :public_fireedge_endpoint: '' will bring the front-end gui (sunstone) to the internal server error.

Best Mike & Merry Christmas :-)

**Comment by tinova** [comment]
That is the correct way to disable FireEdge VNC in Sunstone, please check the note at the end of the first table [in this section](https://docs.opennebula.io/6.8/installation_and_configuration/opennebula_services/sunstone.html#configuration) of the documentation.

**Comment by Githopp192** [comment]
yes, that's where i got it from

https://docs.opennebula.io/6.6/installation_and_configuration/opennebula_services/sunstone.html?highlight=public%20endpoint
