### ISSUE TITLE
Prevent PROBES_PERIOD configuration monitoring errors

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#7659]
**Description**
The probe execution timer configuration is defined in `/etc/one/monitord.conf`. If a probe configuration is missing, it can lead to monitoring errors, resulting in hosts being offline. 
It can be commonly seen now when upgrading from 7.0 to 7.2. A new probe configuration `EXEC_VM` was introduced. If an upgrade is performed in such a way that `onecfg` or the manual community upgrade is done wrong, it can lead to critical failures

**To Reproduce**

- Have 7.2
- Remove EXEC_VM from `/etc/one/monitord.conf`. For example
```
PROBES_PERIOD = [
    BEACON_HOST    = 30,
    SYSTEM_HOST    = 600,
    MONITOR_HOST   = 120,
    STATE_VM       = 5,
    MONITOR_VM     = 30,
    SYNC_STATE_VM  = 180
]
```
- Restart `opennebula`

Now the log file `/var/log/one/monitor.log` should showcase the PROBES_PERIOD configuration being loaded

```
PROBES_PERIOD=BEACON_HOST=30,MONITOR_HOST=120,MONITOR_VM=30,STATE_VM=5,SYNC_STATE_VM=180,SYSTEM_HOST=600
VM_MONITORING_EXPIRATION_TIME=43200
```

When a host is being monitored it will show an error like the following

```log
Thu May  7 18:11:22 2026 [Z0][MDP][I]: Error executing monitord-client_control.sh: #<NoMethodError: undefined method `text' for nil:NilClass>
Thu May  7 18:11:24 2026 [Z0][MDP][I]: Command execution failed (exit code: 1): 'if [ -x "/var/tmp/one/im/run_monitord_client" ]; then /var/tmp/one/im/run_monitord_client kvm 0 localhost; else                              exit 42; fi'
Thu May  7 18:11:24 2026 [Z0][MDP][I]: Error executing monitord-client_control.sh: #<NoMethodError: undefined method `text' for nil:NilClass>
Thu May  7 18:11:27 2026 [Z0][MDP][I]: Command execution failed (exit code: 1): 'if [ -x "/var/tmp/one/im/run_monitord_client" ]; then /var/tmp/one/im/run_monitord_client kvm 0 localhost; else                              exit 42; fi'
Thu May  7 18:11:27 2026 [Z0][MDP][I]: Error executing monitord-client_control.sh: #<NoMethodError: undefined method `text' for nil:NilClass>
Thu May  7 18:11:29 2026 [Z0][MDP][I]: Command execution failed (exit code: 1): 'if [ -x "/var/tmp/one/im/run_monitord_client" ]; then /var/tmp/one/im/run_monitord_client kvm 0 localhost; else                              exit 42; fi'
Thu May  7 18:11:29 2026 [Z0][MDP][I]: Error executing monitord-client_control.sh: #<NoMethodError: undefined method `text' for nil:NilClass>
Thu May  7 18:11:29 2026 [Z0][MDP][W]: Start monitor failed for host 0: Error executing monitord-client_control.sh: #<NoMethodError: undefined method `text' for nil:NilClass>
Thu May  7 18:11:29 2026 [Z0][HMM][E]: Unable to monitor host id: 0
Thu May  7 18:11:29 2026 [Z0][HMM][D]: Updated Host 0, state ERROR
```

**Expected behavior**

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler, or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
